title: Love Sharma # Add a space after the period

#logo: 1.png # Use a relative path to logo image 

description: . # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

#google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: lovemanojsharma@yahoo.com # Allow visitors to contact you
